NOTICE (Updated October 15 2021):

If you maintain scripts used to access ftp.gnu.org over FTP, we strongly
encourage you to change them to use HTTPS instead.

Eventually we hope to shut down FTP protocol access, but plan to give
notice here and other places for several months ahead of time.

--

If you have any problems with the GNU software, please try to contact
the developers of the specific package. If you see a problem with this
website that is not specific to one package, contact
sysadmin@fsf.org. If you are having trouble uploading, contact
ftp-upload@fsf.org. If none of those apply, please refer your questions
to <gnu@gnu.org>.

There are several mirrors of this archive, a complete list can be found
on http://www.gnu.org/order/ftp.html. You might want to use a mirror
closer to you. If you plan to do or cause a lot of automated downloads,
use the mirrors or you can easily disrupt the site and cause your
automated clients to be banned.

Non-GNU programs that were formerly in gnu/ have moved to gnu/non-gnu/.
Most of them were just pointers in the format program.README.  If you
are looking for such a file, be sure to check gnu/non-gnu/.

Archives of the GNU mailing lists can be accessed or downloaded
via the web from http://mail.gnu.org; they are no longer available
by ftp.

The FSF provides this archive as a service to GNU users.  Please
consider donating to the FSF at http://donate.fsf.org/ or becoming an
Associate Member at http://member.fsf.org/.
